---
- name: "3.2.1 | Ensure that the --anonymous-auth argument is set to false (Manual)"
  block:
      - name: Ansible replace --anonymous-auth=true
        replace:
          path: "{{ kubeletconf }}"
          regexp: "--anonymous-auth=true"
          replace: "--anonymous-auth=false"
        notify:
        - restart kubelet
  tags:
      - 3.2.1

- name: "3.2.2 | Ensure that the --authorization-mode argument is not set to AlwaysAllow (Manual)"
  block:
      - name: Ansible replace string --authorization-mode=AlwaysAllow
        replace:
          path: "{{ kubeletconf }}"
          regexp: "--authorization-mode=AlwaysAllow"
          replace: "--authorization-mode=Webhook"
        notify:
        - restart kubelet
  tags:
      - 3.2.2

# - name: "3.2.3 | Ensure that the --client-ca-file argument is set as appropriate (Manual)"
#   block:
#       - name: append --client-ca-file to existing list of KUBELET_FLAGS
#         lineinfile:
#           path: "{{ kubeletconf }}"
#           backrefs: yes
#           regexp: "^(.*KUBELET_FLAGS.*)$"
#           line: "\1 --client-ca-file={{ client-ca-file-path }}""
#         notify:
#         - restart kubelet
  # tags:
  #     - 3.2.3
- name: "3.2.4 | Ensure that the --read-only-port is secured (Manual)"
  block:
      - name: append --read-only-port to existing list of KUBELET_FLAGS
        lineinfile:
          path: "{{ kubeletconf }}"
          backrefs: yes
          regexp: "^(.*KUBELET_FLAGS.*)$"
          line: '\1 --read-only-port=0'
        notify:
        - restart kubelet
  tags:
      - 3.2.4

- name: "3.2.5 | Ensure that the --streaming-connection-idle-timeout argument is not set to 0 (Manual)"
  block:
      - name: append --streaming-connection-idle-timeout to existing list of KUBELET_FLAGS
        lineinfile:
          path: "{{ kubeletconf }}"
          backrefs: yes
          regexp: "^(.*KUBELET_FLAGS.*)$"
          line: '\1 --streaming-connection-idle-timeout=4h0m0s'
        notify:
        - restart kubelet
  tags:
      - 3.2.5

- name: "3.2.6 | Ensure that the --protect-kernel-defaults argument is set to true (Manual)"
  block:
      - name: append --protect-kernel-defaults to existing list of KUBELET_FLAGS
        lineinfile:
          path: "{{ kubeletconf }}"
          backrefs: yes
          regexp: "^(.*KUBELET_FLAGS.*)$"
          line: '\1 --protect-kernel-defaults=true'
        notify:
        - restart kubelet
  tags:
      - 3.2.6

- name: "3.2.7 | Ensure that the --make-iptables-util-chains argument is set to true (Manual)"
  block:
      - name: append --make-iptables-util-chains to existing list of KUBELET_FLAGS
        lineinfile:
          path: "{{ kubeletconf }}"
          backrefs: yes
          regexp: "^(.*KUBELET_FLAGS.*)$"
          line: '\1 --make-iptables-util-chains=true'
        notify:
        - restart kubelet
  tags:
      - 3.2.7

- name: "3.2.8 | Ensure that the --hostname-override argument is not set (Manual)"
  block:
      - name: Ansible replace string --authorization-mode=AlwaysAllow
        replace:
          path: "{{ kubeletconf }}"
          regexp: "--hostname-override"
          replace: ""
        notify:
        - restart kubelet
  tags:
      - 3.2.8

- name: "3.2.9 | Ensure that the --eventRecordQPS argument is set to 0 or a level which ensures appropriate event capture (Manual)"
  block:
      - name: append --event-qps to existing list of KUBELET_FLAGS
        lineinfile:
          path: "{{ kubeletconf }}"
          backrefs: yes
          regexp: "^(.*KUBELET_FLAGS.*)$"
          line: '\1 --event-qps=0 '
        notify:
        - restart kubelet
  tags:
      - 3.2.9

- name: "3.2.10 | Ensure that the --rotate-certificates argument is not set to false (Manual)"
  block:
      - name: Ansible replace string --rotate-certificates
        replace:
          path: "{{ kubeletconf }}"
          regexp: "--rotate-certificates=false"
          replace: "--rotate-certificates=true"
        notify:
        - restart kubelet
  tags:
      - 3.2.10

- name: "3.2.11 | Ensure that the RotateKubeletServerCertificate argument is set to true (Manual)"
  block:
      - name: append --rotate-kubelet-server-certificate=true to existing list of KUBELET_FLAGS
        lineinfile:
          path: "{{ kubeletconf }}"
          backrefs: yes
          regexp: "^(.*KUBELET_FLAGS.*)$"
          line: '\1 --rotate-kubelet-server-certificate=true'
        notify:
        - restart kubelet
  tags:
      - 3.2.11