---
- name: Check ansible version
  fail:
      msg: You must use ansible 2.9 or greater
  when: not ansible_version.full is version_compare('2.9', '>=')

- name: Gather the package facts
  package_facts:
      manager: auto

# - name: Import section 1 tasks
#   import_tasks: section_1/main.yml


# - name: Import section 2 tasks
#   import_tasks: section_2/main.yml

- name: Import section 3 tasks
  import_tasks: section_3/main.yml


# - name: Import section 4 tasks
#   import_tasks: section_4/main.yml


# - name: Import section 5 tasks
#   import_tasks: section_5/main.yml
