---

- name: Import section 1 tasks
  import_tasks: section1/main.yml
  when: inventory_hostname in groups["masters"]

- name: Import section 2 tasks
  import_tasks: section2/main.yml
  when: inventory_hostname in groups["masters"]

- name: Import section 3 tasks
  import_tasks: section3/main.yml
  when: inventory_hostname in groups["masters"]

- name: Import section 4 tasks
  import_tasks: section4/main.yml
  when: inventory_hostname in groups["workers"]

- name: Apply Page Template On Masters Node
  local_action: template src=master_output_template.html.j2 dest={{ report_default_path }}/master_benchmark_{{ ansible_date_time.date }}.html
  become: false
  when: inventory_hostname in groups["masters"]

- name: Apply Page Template On Worker
  local_action: template src=worker_output_template.html.j2 dest={{ report_default_path }}/worker_benchmark_{{ ansible_date_time.date }}.html
  become: false
  when: inventory_hostname in groups["workers"]

- debug: msg="the current date is {{ ansible_date_time.date }}"


