---
- name: "3.1.x | PRE | Check to see if the Kubelet Service is running"
  command: "systemctl status kubelet"
  register: aks_kubelet_active

- name: "3.1.1 | Ensure that the kubeconfig file permissions are set to 644 or more
restrictive (Manual)"
  block:
      - command: "stat -c %a {{ kubeletkubeconfig }}"
        when: "'active' in aks_kubelet_active.stdout"
        register: result311

      - name: Get PASSED result
        set_fact:
          section3_tasks: '{{ section3_tasks | default([]) + [{ "task_number":"3.1.1","task_description":"Ensure that the kubeconfig file permissions are set to 644 or more restrictive (Manual)","task_status":"PASSED","configuration":"","script":"" }] }}'
        when: 
          - result311.stdout == '644'

      - name: Get FAILED result
        set_fact:
          section3_tasks: '{{ section3_tasks | default([]) + [{ "task_number":"3.1.1","task_description":"Ensure that the kubeconfig file permissions are set to 644 or more restrictive (Manual)","task_status":"FAILED","configuration":result311.stdout,"script":"Fix it" }] }}'
        when: 
          - result311.stdout != '644'

  tags:
      - level
      - rule_3.1.1
      - audit
      - worker

- name: "3.1.2 | Ensure that the kubelet kubeconfig file ownership is set to root:root (Manual)"
  block:
      - command: "stat -c %U:%G {{ kubeletkubeconfig }}"
        when: "'active' in aks_kubelet_active.stdout"
        register: result312

      - name: Get PASSED result
        set_fact:
          section3_tasks: '{{ section3_tasks | default([]) + [{ "task_number":"3.1.2","task_description":"Ensure that the kubelet kubeconfig file ownership is set to root:root (Manual)","task_status":"PASSED","configuration":"","script":"" }] }}'
        when: 
          - result312.stdout == 'root:root'

      - name: Get FAILED result
        set_fact:
          section3_tasks: '{{ section3_tasks | default([]) + [{ "task_number":"3.1.2","task_description":"Ensure that the kubelet kubeconfig file ownership is set to root:root (Manual)","task_status":"FAILED","configuration":result312.stdout,"script":"Fix it" }] }}'
        when: 
          - result312.stdout != 'root:root'

  tags:
      - level
      - rule_3.1.2
      - audit
      - worker

- name: "3.1.3 | Ensure that the kubelet configuration file has permissions set to 644 or more restrictive (Manual)"
  block:
      - command: "stat -c %a {{ kubeletconf }}"
        when: "'active' in aks_kubelet_active.stdout"
        register: result313

      - name: Get PASSED result
        set_fact:
          section3_tasks: '{{ section3_tasks | default([]) + [{ "task_number":"3.1.3","task_description":"Ensure that the kubelet configuration file has permissions set to 644 or more restrictive (Manual)","task_status":"PASSED","configuration":"","script":"" }] }}'
        when: 
          - result313.stdout == '644'

      - name: Get FAILED result
        set_fact:
          section3_tasks: '{{ section3_tasks | default([]) + [{ "task_number":"3.1.3","task_description":"Ensure that the kubelet configuration file has permissions set to 644 or more restrictive (Manual)","task_status":"FAILED","configuration":result313.stdout,"script":"Fix it" }] }}'
        when: 
        - result313.stdout != '644'

  tags:
      - level
      - rule_3.1.3
      - audit
      - worker

- name: "3.1.4 | Ensure that the kubelet configuration file ownership is set to root:root (Manual)"
  block:
      - command: "stat -c %U:%G {{ kubeletconf }}"
        when: "'active' in aks_kubelet_active.stdout"
        register: result314

      - name: Get PASSED result
        set_fact:
          section3_tasks: '{{ section3_tasks | default([]) + [{ "task_number":"3.1.4","task_description":"Ensure that the kubelet configuration file ownership is set to root:root (Manual)","task_status":"PASSED","configuration":"","script":"" }] }}'
        when: 
          - result314.stdout == 'root:root'

      - name: Get FAILED result
        set_fact:
          section3_tasks: '{{ section3_tasks | default([]) + [{ "task_number":"3.1.4","task_description":"Ensure that the kubelet configuration file ownership is set to root:root (Manual)","task_status":"PASSED","configuration":result314.stdout,"script":"Fix it" }] }}'
        when: 
        - result314.stdout != 'root:root'

  tags:
      - level
      - rule_3.1.4
      - audit
      - worker

