---
- name: "4.7.1 | Create administrative boundaries between resources using namespaces (Manual)"
  block:
      - shell: "kubectl get namespaces | awk 'BEGIN { ORS=\"; \" }; {if (NR!=1) print $1 }'"
        register: result471

      - debug:
          msg: "4.7.1 | NOT SCORED | Create administrative boundaries between resources using namespaces (Manual)."
      - lineinfile:
          line: "4.7.1 | NOT SCORED | Create administrative boundaries between resources using namespaces (Manual).\n- Namespaces found: {{ result471.stdout | default(0) }}"
          insertafter: EOF
          dest: "{{ report_path }}"
          create: yes
        delegate_to: 127.0.0.1
  delegate_to: 127.0.0.1

- name: "4.7.2 | Apply Security Context to Your Pods and Containers (Manual)"
  block:
      - debug:
          msg: "4.7.2 | NOT SCORED | Apply Security Context to Your Pods and Containers (Manual)."
      - lineinfile:
          line: "4.7.2 | NOT SCORED | Apply Security Context to Your Pods and Containers (Manual).\n- Audit: Review the pod definitions in your cluster and verify that you have security contexts defined as appropriate."
          insertafter: EOF
          dest: "{{ report_path }}"
          create: yes
        delegate_to: 127.0.0.1
  delegate_to: 127.0.0.1

- name: "4.7.3 | The default namespace should not be used (Manual)"
  block:
      - shell: "kubectl get all -n default | awk 'BEGIN { ORS=\"; \" }; {if (NR!=1) print $1 }'"
        register: result471

      - debug:
          msg: "4.7.1 | NOT SCORED | The default namespace should not be used (Manual)."
      - lineinfile:
          line: "4.7.1 | NOT SCORED | The default namespace should not be used (Manual).\n- Resource found in default: {{ result473.stdout | default(0) }}"
          insertafter: EOF
          dest: "{{ report_path }}"
          create: yes
        delegate_to: 127.0.0.1
  delegate_to: 127.0.0.1