---

- name: Set report file name
  set_fact: report_path="{{ report_default_path }}/cis_bench_report-{{ ansible_date_time.date }}.txt"

- name: Generate report file
  lineinfile:
    dest: "{{ csv_path }}/{{ csv_filename }}"
    line: "{{ headers }}"
    create: true
    state: present
  delegate_to: localhost
  run_once: true

- name: Check ansible version
  fail:
      msg: You must use ansible 2.9 or greater
  when: not ansible_version.full is version_compare('2.9', '>=')

- name: Gather the package facts
  package_facts:
      manager: auto

- name: Import section 1 tasks
  import_tasks: section_1/main.yml
  when: akscis_section1
  tags:
      - akscis_section1

- name: Import section 2 tasks
  import_tasks: section_2/main.yml
  tags:
      - akscis_section2
  when: akscis_section2

- name: Import section 3 tasks
  import_tasks: section_3/main.yml
  when: akscis_section3
  tags:
      - akscis_section3

# - name: Import section 4 tasks
#   import_tasks: section_4/main.yml
#   when: akscis_section4
#   tags:
#       - akscis_section4

# - name: Import section 5 tasks
#   import_tasks: section_5/main.yml
#   when: akscis_section5
#   tags:
#       - akscis_section5

# - name: Count fail tasks
#   shell: "cat {{ report_path }} | grep FAILED | wc -l | awk '{print \"Fail: \" $0 \" tasks\"}' >> \"{{ report_path }}\""
#   delegate_to: 127.0.0.1

# - name: Count scored tasks
#   shell: "cat {{ report_path }} | grep PASS | wc -l | awk '{print \"Passed: \" $0 \" tasks\"}' >> \"{{ report_path }}\""
#   delegate_to: 127.0.0.1

# - name: Count total tasks
#   shell: "cat {{ report_path }} | grep -E \"[0-9 ]+.\\|\" | grep -v 'NOT SCORED' | wc -l | awk '{print \"Total: \" $0 \" tasks\"}' >> \"{{ report_path }}\""
#   delegate_to: 127.0.0.1

# - name: Count not scored tasks
#   shell: "cat {{ report_path }} | grep 'NOT SCORED' | wc -l | awk '{print \"Not Scored: \" $0 \" tasks\"}' >> \"{{ report_path }}\""
#   delegate_to: 127.0.0.1

- name: Read in CSV to variable
  community.general.read_csv:
    path: "{{ csv_path }}/{{ csv_filename }}"
  register: csv_file
  delegate_to: localhost
  run_once: true

- name: Generate HTML report
  template:
    src: templates/report.html.j2
    dest: "{{ report_default_path }}/report.html"
  delegate_to: 127.0.0.1

