---
- name: "2.1.1 | Enable audit Logs (Manual)"
  block:
      - name: Get NOT SCORED result
        set_fact:
          section2_tasks: '{{ section1_tasks | default([]) + [{ "task_number":"2.1.1","task_description":"Enable audit Logs (Manual)","task_status":"NOT SCORED","configuration":"","script":"" }] }}'

  delegate_to: 127.0.0.1
