---
- name: "2.1.1 | Enable audit Logs (Manual)"
  block:
      # - debug:
      #     msg: "2.1.1 | NOT SCORED | Enable audit Logs (Manual)."
        
      # - name: Create report line
      #   block:
      #     - lineinfile:
      #         line: "2.1.1 | NOT SCORED | Enable audit Logs (Manual)"
      #         insertafter: EOF
      #         dest: "{{ report_path }}"
      #         create: yes
      #     - set_fact:
      #         report_data: '{{ report_data | default([]) + [{ "task_number":"2.1.1","task_description":"Enable audit Logs (Manual)","status":"not scored","configuration":"","remediation":"Script here" }] }}'
      #   delegate_to: 127.0.0.1

      - name: Get NOT SCORED result
        set_fact:
          report_data: '{{ report_data | default([]) + [{ "task_number":"2.1.1","task_description":"Enable audit Logs (Manual)","status":"NOT SCORED","configuration":"","remediation":"Script here" }] }}'

  delegate_to: 127.0.0.1
