---
- name: "SECTION | 1 | Master (Control Plane) Components"
  block:
      # - debug:
      #     msg: "1.0.0 | NOT SCORED | Master (Control Plane) Components."

      # - lineinfile:
      #     line: "1.0.0 | NOT SCORED | Master (Control Plane) Components"
      #     insertafter: EOF
      #     dest: "{{ report_path }}"
      #     create: yes
      #   delegate_to: 127.0.0.1

      - name: Get NOT SCORED result
        set_fact:
          report_data: '{{ report_data | default([]) + [{ "task_number":"1.0.0","task_description":"Master (Control Plane) Components","status":"NOT SCORED","configuration":"","remediation":"Script here" }] }}'

  delegate_to: 127.0.0.1
