---
- name: "5.6.1 | Restrict untrusted workloads (Manual)"
  block:
      - debug:
          msg: "5.6.1 | NOT SCORED | Restrict untrusted workloads (Manual)."
      - lineinfile:
          line: "5.6.1 | NOT SCORED | Restrict untrusted workloads (Manual)."
          insertafter: EOF
          dest: "{{ report_path }}"
          create: yes
        delegate_to: 127.0.0.1
  delegate_to: 127.0.0.1

- name: "5.6.2 | Hostile multi-tenant workloads (Manual)"
  block:
      - debug:
          msg: "5.6.2 | NOT SCORED | Hostile multi-tenant workloads (Manual)."
      - lineinfile:
          line: "5.6.2 | NOT SCORED | Hostile multi-tenant workloads (Manual)."
          insertafter: EOF
          dest: "{{ report_path }}"
          create: yes
        delegate_to: 127.0.0.1
  delegate_to: 127.0.0.1