---
- name: "5.2.1 | Prefer using dedicated AKS Service Accounts (Manual)"
  block:
      - debug:
          msg: "5.2.1 | NOT SCORED | Prefer using dedicated AKS Service Accounts (Manual)."
      - name: Get NOT SCORED result
        set_fact:
          section5_tasks: '{{ section5_tasks | default([]) + [{ "task_number":"5.2.1","task_description":" Prefer using dedicated AKS Service Accounts (Manual)","task_status":"NOT SCORED","configuration":"","script":"" }] }}'

  delegate_to: 127.0.0.1
  become: false
