---
- name: "5.2.1 | Prefer using dedicated AKS Service Accounts (Manual)"
  block:
      - debug:
          msg: "5.2.1 | NOT SCORED | Prefer using dedicated AKS Service Accounts (Manual)."
      - name: Get NOT SCORED result
        set_fact:
          report_data: '{{ report_data | default([]) + [{ "task_number":"5.2.1","task_description":" Prefer using dedicated AKS Service Accounts (Manual)","status":"NOT SCORED","configuration":"","remediation":"Script here" }] }}'

  delegate_to: 127.0.0.1
