---
- name: "5.6.1 | Restrict untrusted workloads (Manual)"
  block:
      - debug:
          msg: "5.6.1 | NOT SCORED | Restrict untrusted workloads (Manual)."
      - name: Get NOT SCORED result
        set_fact:
          section5_tasks: '{{ section5_tasks | default([]) + [{ "task_number":"5.6.1","task_description":"Restrict untrusted workloads (Manual)","task_status":"NOT SCORED","configuration":"","script":"" }] }}'

  delegate_to: 127.0.0.1
  become: false

- name: "5.6.2 | Hostile multi-tenant workloads (Manual)"
  block:
      - debug:
          msg: "5.6.2 | NOT SCORED | Hostile multi-tenant workloads (Manual)."
      - name: Get NOT SCORED result
        set_fact:
          section5_tasks: '{{ section5_tasks | default([]) + [{ "task_number":"5.6.2","task_description":"Hostile multi-tenant workloads (Manual)","task_status":"NOT SCORED","configuration":"","script":"" }] }}'

  delegate_to: 127.0.0.1
  become: false