---
- name: "3.1.x | PRE | Check to see if the Kubelet Service is running"
  command: "systemctl status kubelet"
  register: aks_kubelet_active

- name: "3.1.1 | Ensure that the kubeconfig file permissions are set to 644 or more
restrictive (Manual)"
  block:
      - command: "stat -c %a {{ kubeletkubeconfig }}"
        when: "'active' in aks_kubelet_active.stdout"
        register: result311

      - debug:
          msg: "{% if result311.stdout == '644' %}3.1.1 | PASSED | Ensure that the kubeconfig file permissions are set to 644 or more restrictive (Manual){% else %}3.1.1 | FAILED | Ensure that the kubeconfig file permissions are set to 644 or more restrictive (Manual){% endif %}"

      - name: Get output string
        set_fact:
          output: "{% if result311.stdout == '644' %}3.1.1,Ensure that the kubeconfig file permissions are set to 644 or more restrictive (Manual),PASSED{% else %}3.1.1,Ensure that the kubeconfig file permissions are set to 644 or more restrictive (Manual),FAILED{% endif %}"

      - name: Append output string to list
        set_fact:
          section_3_lists: "{{ section_3_lists + [ output ] }}"

      # - lineinfile:
      #     line: "{% if result311.stdout == '644' %}3.1.1,Ensure that the kubeconfig file permissions are set to 644 or more restrictive (Manual),PASSED{% else %}3.1.1,Ensure that the kubeconfig file permissions are set to 644 or more restrictive (Manual),FAILED{% endif %}"
      #     dest: "{{ csv_path }}/{{ csv_filename }}"
      #     create: true
      #     state: present
      #   delegate_to: localhost

  tags:
      - level
      - rule_3.1.1
      - audit
      - worker

- name: "3.1.2 | Ensure that the kubelet kubeconfig file ownership is set to root:root (Manual)"
  block:
      - command: "stat -c %U:%G {{ kubeletkubeconfig }}"
        when: "'active' in aks_kubelet_active.stdout"
        register: result312

      - debug:
          msg: "{% if result312.stdout == 'root:root' %}3.1.2 | PASSED | Ensure that the kubelet kubeconfig file ownership is set to root:root (Manual){% else %}3.1.2 | FAILED | Ensure that the kubelet kubeconfig file ownership is set to root:root (Manual){% endif %}"
      
      - name: Get output string
        set_fact:
          output: "{% if result312.stdout == 'root:root' %}3.1.2,Ensure that the kubelet kubeconfig file ownership is set to root:root (Manual),PASSED{% else %}3.1.2,Ensure that the kubelet kubeconfig file ownership is set to root:root (Manual),FAILED{% endif %}"

      - name: Append output string to list
        set_fact:
          section_3_lists: "{{ section_3_lists + [ output ] }}"

      # - lineinfile:
      #     line: "{% if result312.stdout == 'root:root' %}3.1.2,Ensure that the kubelet kubeconfig file ownership is set to root:root (Manual),PASSED{% else %}3.1.2,Ensure that the kubelet kubeconfig file ownership is set to root:root (Manual),FAILED{% endif %}"
      #     dest: "{{ csv_path }}/{{ csv_filename }}"
      #     create: true
      #     state: present
      #   delegate_to: 127.0.0.1

  tags:
      - level
      - rule_3.1.2
      - audit
      - worker

- name: "3.1.3 | Ensure that the kubelet configuration file has permissions set to
644 or more restrictive (Manual)"
  block:
      - command: "stat -c %a {{ kubeletconf }}"
        when: "'active' in aks_kubelet_active.stdout"
        register: result313

      - debug:          
          msg: "{% if result313.stdout == '644' %}3.1.3 | PASSED | Ensure that the kubelet configuration file has permissions set to 644 or more restrictive (Manual){% else %}3.1.3 | FAILED | Ensure that the kubelet configuration file has permissions set to 644 or more restrictive (Manual){% endif %}"

      - name: Get output string
        set_fact:
          output: "{% if result313.stdout == '644' %}3.1.3,Ensure that the kubelet configuration file has permissions set to 644 or more restrictive (Manual),PASSED{% else %}3.1.3,Ensure that the kubelet configuration file has permissions set to 644 or more restrictive (Manual),FAILED{% endif %}"

      - name: Append output string to list
        set_fact:
          section_3_lists: "{{ section_3_lists + [ output ] }}"

      # - lineinfile:
      #     line: "{% if result313.stdout == '644' %}3.1.3,Ensure that the kubelet configuration file has permissions set to 644 or more restrictive (Manual),PASSED{% else %}3.1.3,Ensure that the kubelet configuration file has permissions set to 644 or more restrictive (Manual),FAILED{% endif %}"
      #     dest: "{{ csv_path }}/{{ csv_filename }}"
      #     create: true
      #     state: present
      #   delegate_to: 127.0.0.1
  tags:
      - level
      - rule_3.1.3
      - audit
      - worker

- name: "3.1.4 | Ensure that the kubelet configuration file ownership is set to root:root (Manual)"
  block:
      - command: "stat -c %U:%G {{ kubeletconf }}"
        when: "'active' in aks_kubelet_active.stdout"
        register: result314

      - debug:
          msg: "{% if result314.stdout == 'root:root' %}3.1.4 | PASSED | Ensure that the kubelet configuration file ownership is set to root:root (Manual){% else %}3.1.4 | FAILED | Ensure that the kubelet configuration file ownership is set to root:root (Manual){% endif %}"
      
      - name: Get output string
        set_fact:
          output: "{% if result314.stdout == 'root:root' %}3.1.4,Ensure that the kubelet configuration file ownership is set to root:root (Manual),PASSED{% else %}3.1.4,Ensure that the kubelet configuration file ownership is set to root:root (Manual),FAILED{% endif %}"

      - name: Append output string to list
        set_fact:
          section_3_lists: "{{ section_3_lists + [ output ] }}"
      
      # - lineinfile:
      #     line: "{% if result314.stdout == 'root:root' %}3.1.4,Ensure that the kubelet configuration file ownership is set to root:root (Manual),PASSED{% else %}3.1.4,Ensure that the kubelet configuration file ownership is set to root:root (Manual),FAILED{% endif %}"
      #     dest: "{{ csv_path }}/{{ csv_filename }}"
      #     create: true
      #     state: present
      #   delegate_to: 127.0.0.1

  tags:
      - level
      - rule_3.1.4
      - audit
      - worker


- name: Export csv output
  lineinfile:
    line: "{{ item }}"
    dest: "{{ csv_path }}/{{ csv_filename }}"
    create: true
    state: present
  with_items:
    - "{{ section_3_lists }}"
  delegate_to: 127.0.0.1