---
- name: "3.2.x | PRE | Check to see if the Kubelet Service is running"
  command: "systemctl status kubelet"
  register: aks_kubelet_active

- name: "3.2.x | PRE | Get argument from kubelet binary"
  command: "/bin/ps -fC {{ kubeletbin }}"
  when: "'active' in aks_kubelet_active.stdout"
  register: result32bin

- name: "3.2.x | PRE | Get argument from kubelet configuration file"
  command: "/bin/cat {{ kubeletconf }}"
  when: "'active' in aks_kubelet_active.stdout"
  register: result32cfg

- name: "3.2.1 | Ensure that the --anonymous-auth argument is set to false (Manual)"
  block:
      - debug:
          msg: "{% if result32bin.stdout == '--anonymous-auth=false' or result32cfg.stdout == '--anonymous-auth=false' %} 3.2.1 | PASSED | Ensure that the --anonymous-auth argument is set to false (Manual){% else %}3.2.1 | FAILED | Ensure that the --anonymous-auth argument is set to false (Manual){% endif %}"

      - lineinfile:
          line:  "{% if result32bin.stdout == '--anonymous-auth=false' or result32cfg.stdout == '--anonymous-auth=false' %} 3.2.1,Ensure that the --anonymous-auth argument is set to false (Manual),PASSED{% else %}3.2.1,Ensure that the --anonymous-auth argument is set to false (Manual),FAILED{% endif %}"
          dest: "{{ csv_path }}/{{ csv_filename }}"
          create: true
          state: present
        delegate_to: 127.0.0.1

  tags:
      - level
      - rule_3.2.1
      - audit
      - worker

- name: "3.2.2 | Ensure that the --authorization-mode argument is not set to AlwaysAllow (Manual)"
  block:
      - debug: 
          msg: "{% if ('--authorization-mode=AlwaysAllow' not in result32bin.stdout) and ('--authorization-mode=AlwaysAllow' not in result32cfg.stdout) %}3.2.2 | PASSED | Ensure that the --authorization-mode argument is not set to AlwaysAllow (Manual){% else %}3.2.2 | FAILED | Ensure that the --authorization-mode argument is not set to AlwaysAllow (Manual){% endif %}"

      - lineinfile:
          line: "{% if ('--authorization-mode=AlwaysAllow' not in result32bin.stdout) and ('--authorization-mode=AlwaysAllow' not in result32cfg.stdout) %}3.2.2,Ensure that the --authorization-mode argument is not set to AlwaysAllow (Manual),PASSED{% else %}3.2.2,Ensure that the --authorization-mode argument is not set to AlwaysAllow (Manual),FAILED{% endif %}"
          dest: "{{ csv_path }}/{{ csv_filename }}"
          create: true
          state: present
        delegate_to: 127.0.0.1
  
  tags:
      - level
      - rule_3.2.2
      - audit
      - worker

- name: "3.2.3 | Ensure that the --client-ca-file argument is set as appropriate (Manual)"
  block:
      - debug: 
          msg: "{% if ('--client-ca-file' in result32bin.stdout) or ('--client-ca-file' in result32cfg.stdout) %}3.2.3 | PASSED | Ensure that the --client-ca-file argument is set as appropriate (Manual){% else %}3.2.3 | FAILED | Ensure that the --client-ca-file argument is set as appropriate (Manual){% endif %}"

      - lineinfile:
          line: "{% if ('--client-ca-file' in result32bin.stdout) or ('--client-ca-file' in result32cfg.stdout) %}3.2.3,Ensure that the --client-ca-file argument is set as appropriate (Manual),PASSED{% else %}3.2.3,Ensure that the --client-ca-file argument is set as appropriate (Manual),FAILED{% endif %}"
          dest: "{{ csv_path }}/{{ csv_filename }}"
          create: true
          state: present
        delegate_to: 127.0.0.1

  tags:
      - level
      - rule_3.2.3
      - audit
      - worker

- name: "3.2.4 | Ensure that the --read-only-port is secured (Manual)"
  block:
      - debug: 
          msg: "{% if ('--read-only-port=0' in result32bin.stdout) or ('--read-only-port=0' in result32cfg.stdout) %}3.2.4 | PASSED | Ensure that the --read-only-port is secured (Manual){% else %}3.2.4 | FAILED | Ensure that the --read-only-port is secured (Manual){% endif %}"

      - lineinfile:
          line: "{% if ('--read-only-port=0' in result32bin.stdout) or ('--read-only-port=0' in result32cfg.stdout) %}3.2.4,Ensure that the --read-only-port is secured (Manual),PASSED{% else %}3.2.4,Ensure that the --read-only-port is secured (Manual),FAILED{% endif %}"
          dest: "{{ csv_path }}/{{ csv_filename }}"
          create: true
          state: present
        delegate_to: 127.0.0.1

  tags:
      - level
      - rule_3.2.4
      - audit
      - worker

- name: "3.2.5 | Ensure that the --streaming-connection-idle-timeout argument is not set to 0 (Manual)"
  block:
      - debug: 
          msg: "{% if ('--streaming-connection-idle-timeout=0' not in result32bin.stdout) and ('--streaming-connection-idle-timeout=0' not in result32cfg.stdout) %}3.2.5 | PASSED | Ensure that the --streaming-connection-idle-timeout argument is not set to 0 (Manual){% else %}3.2.5 | FAILED | Ensure that the --streaming-connection-idle-timeout argument is not set to 0 (Manual){% endif %}"

      - lineinfile:
          line: "{% if ('--streaming-connection-idle-timeout=0' not in result32bin.stdout) and ('--streaming-connection-idle-timeout=0' not in result32cfg.stdout) %}3.2.5,Ensure that the --streaming-connection-idle-timeout argument is not set to 0 (Manual),PASSED{% else %}3.2.5,Ensure that the --streaming-connection-idle-timeout argument is not set to 0 (Manual),FAILED{% endif %}"
          dest: "{{ csv_path }}/{{ csv_filename }}"
          create: true
          state: present
        delegate_to: 127.0.0.1

  tags:
      - level
      - rule_3.2.5
      - audit
      - worker

- name: "3.2.6 | Ensure that the --protect-kernel-defaults argument is set to true (Manual)"
  block:
      - debug: 
          msg: "{% if ('--protect-kernel-defaults=true' in result32bin.stdout) or ('--protect-kernel-defaults=true' in result32cfg.stdout) %}3.2.6 | PASSED | Ensure that the --protect-kernel-defaults argument is set to true (Manual){% else %}3.2.6 | FAILED | Ensure that the --protect-kernel-defaults argument is set to true (Manual){% endif %}"

      - lineinfile:
          line: "{% if ('--protect-kernel-defaults=true' in result32bin.stdout) or ('--protect-kernel-defaults=true' in result32cfg.stdout) %}3.2.6 | PASSED | Ensure that the --protect-kernel-defaults argument is set to true (Manual){% else %}3.2.6 | FAILED | Ensure that the --protect-kernel-defaults argument is set to true (Manual){% endif %}"
          dest: "{{ csv_path }}/{{ csv_filename }}"
          create: true
          state: present
        delegate_to: 127.0.0.1

  tags:
      - level
      - rule_3.2.6
      - audit
      - worker

- name: "3.2.7 | Ensure that the --make-iptables-util-chains argument is set to true (Manual)"
  block:
      - debug: 
          msg: "{% if ('--make-iptables-util-chains=true' in result32bin.stdout) or ('--make-iptables-util-chains=true' in result32cfg.stdout) %}3.2.7 | PASSED | Ensure that the --make-iptables-util-chains argument is set to true (Manual){% else %}3.2.7 | FAILED | Ensure that the --make-iptables-util-chains argument is set to true (Manual){% endif %}"

      - lineinfile:
          line: "{% if ('--make-iptables-util-chains=true' in result32bin.stdout) or ('--make-iptables-util-chains=true' in result32cfg.stdout) %}3.2.7 | PASSED | Ensure that the --make-iptables-util-chains argument is set to true (Manual){% else %}3.2.7 | FAILED | Ensure that the --make-iptables-util-chains argument is set to true (Manual){% endif %}"
          dest: "{{ csv_path }}/{{ csv_filename }}"
          create: true
          state: present
        delegate_to: 127.0.0.1

  tags:
      - level
      - rule_3.2.7
      - audit
      - worker

- name: "3.2.8 | Ensure that the --hostname-override argument is not set (Manual)"
  block:
      - debug: 
          msg: "{% if ('--hostname-override' not in result32bin.stdout) and ('--hostname-override' not in result32cfg.stdout) %}3.2.8 | PASSED | Ensure that the --hostname-override argument is not set (Manual){% else %}3.2.8 | FAILED | Ensure that the --hostname-override argument is not set (Manual){% endif %}"

      - lineinfile:
          line: "{% if ('--hostname-override' not in result32bin.stdout) and ('--hostname-override' not in result32cfg.stdout) %}3.2.8 | PASSED | Ensure that the --hostname-override argument is not set (Manual){% else %}3.2.8 | FAILED | Ensure that the --hostname-override argument is not set (Manual){% endif %}"
          dest: "{{ csv_path }}/{{ csv_filename }}"
          create: true
          state: present
        delegate_to: 127.0.0.1

  tags:
      - level
      - rule_3.2.8
      - audit
      - worker

- name: "3.2.9 | Ensure that the --eventRecordQPS argument is set to 0 or a level which ensures appropriate event capture (Manual)"
  block:
      - debug: 
          msg: "{% if ('--event-qps=0' in result32bin.stdout) or ('--event-qps=0' in result32cfg.stdout) %}3.2.9 | PASSED | Ensure that the --eventRecordQPS argument is set to 0 or a level which ensures appropriate event capture (Manual){% else %}3.2.9 | FAILED | Ensure that the --eventRecordQPS argument is set to 0 or a level which ensures appropriate event capture (Manual){% endif %}"

      - lineinfile:
          line: "{% if ('--event-qps=0' in result32bin.stdout) or ('--event-qps=0' in result32cfg.stdout) %}3.2.9 | PASSED | Ensure that the --eventRecordQPS argument is set to 0 or a level which ensures appropriate event capture (Manual){% else %}3.2.9 | FAILED | Ensure that the --eventRecordQPS argument is set to 0 or a level which ensures appropriate event capture (Manual){% endif %}"
          dest: "{{ csv_path }}/{{ csv_filename }}"
          create: true
          state: present
        delegate_to: 127.0.0.1
  tags:
      - level
      - rule_3.2.9
      - audit
      - worker

- name: "3.2.10 | Ensure that the --rotate-certificates argument is not set to false (Manual)"
  block:
      - debug: 
          msg: "{% if ('--rotate-certificates=false' not in result32bin.stdout) and ('--rotate-certificates=false' not in result32cfg.stdout) %}3.2.10| PASSED | Ensure that the --rotate-certificates argument is not set to false (Manual){% else %}3.2.10| PASSED | Ensure that the --rotate-certificates argument is not set to false (Manual){% endif %}"

      - lineinfile:
          line: "{% if ('--rotate-certificates=false' not in result32bin.stdout) and ('--rotate-certificates=false' not in result32cfg.stdout) %}3.2.10| PASSED | Ensure that the --rotate-certificates argument is not set to false (Manual){% else %}3.2.10| PASSED | Ensure that the --rotate-certificates argument is not set to false (Manual){% endif %}"
          dest: "{{ csv_path }}/{{ csv_filename }}"
          create: true
          state: present
        delegate_to: 127.0.0.1

  tags:
      - level
      - rule_3.2.10
      - audit
      - worker

- name: "3.2.11 | Ensure that the RotateKubeletServerCertificate argument is set to true (Manual)"
  block:
      - debug: 
          msg: "{% if ('--rotate-kubelet-server-certificate=true' in result32bin.stdout) or ('--rotate-kubelet-server-certificate=true' in result32cfg.stdout) %}3.2.11| PASSED | Ensure that the RotateKubeletServerCertificate argument is set to true (Manual){% else %}3.2.11| FAILED | Ensure that the RotateKubeletServerCertificate argument is set to true (Manual){% endif %}"

      - lineinfile:
          line: "{% if ('--rotate-kubelet-server-certificate=true' in result32bin.stdout) or ('--rotate-kubelet-server-certificate=true' in result32cfg.stdout) %}3.2.11| PASSED | Ensure that the RotateKubeletServerCertificate argument is set to true (Manual){% else %}3.2.11| FAILED | Ensure that the RotateKubeletServerCertificate argument is set to true (Manual){% endif %}"
          dest: "{{ csv_path }}/{{ csv_filename }}"
          create: true
          state: present
        delegate_to: 127.0.0.1

  tags:
      - level
      - rule_3.2.11
      - audit
      - worker