---
- name: AKS Benchmark
  hosts: aks

  vars:
    report_default_path: "/home/trind/ansible-projects/cis-bench-k8s-ansible/CISBenchApp/application/templates/result/aks"
    
  roles:
      - aks-bench