---

- name: Minikube Benchmark
  hosts: k8s
  become: true
  # edit report path
  vars:
    report_default_path: "/home/ubuntu/Desktop/cis-bench-k8s-ansible/CISBenchApp/application/templates/result/minikube"
  roles:
      - k8s-bench