- name: "4.1.1 | Ensure that the cluster-admin role is only used where required (Manual)"
  block:
      - shell: "kubectl get clusterrolebindings -o=custom-columns=NAME:.metadata.name,ROLE:.roleRef.name,SUBJECT:.subjects[*].name | grep cluster-admin | awk 'BEGIN { ORS=\" \" }; {print NR \".\"$1}'"
        register: result411

      - debug:
          msg: "4.1.1 | FAILED | Ensure that the cluster-admin role is only used where required (Manual).\n- Found: {{ result411.stdout | default(0) }}"

      - name: Get FAILED result
        set_fact:
          section4_tasks: '{{ section4_tasks | default([]) + [{ "task_number":"4.1.1","task_description":"Ensure that the cluster-admin role is only used where required (Manual)","task_status":"FAILED","configuration":result411.stdout,"script":"" }] }}'

  delegate_to: 127.0.0.1
  become: false


- name: "4.1.2 | Minimize access to secrets (Manual)"
  block:
      - shell: "kubectl api-resources --sort-by name -o wide | grep secret | cut -d'[' -f 2 | sed 's/.$//'"
        register: result412

      - debug:
          msg: "4.1.2 | FAILED | Minimize access to secrets (Manual).\n- Found: {{ result412.stdout | default(0) }}"

      - name: Get FAILED result
        set_fact:
          section4_tasks: '{{ section4_tasks | default([]) + [{ "task_number":"4.1.2","task_description":"Minimize access to secrets (Manual)","task_status":"FAILED","configuration":result412.stdout,"script":"" }] }}'

  delegate_to: 127.0.0.1
  become: false

- name: "4.1.3 | Minimize wildcard use in Roles and ClusterRoles (Manual)"
  block:
      - shell: "kubectl get roles --all-namespaces -o yaml | grep -q '*' && echo 'Found wildcard in Roles'; kubectl get clusterroles -o yaml | grep -q '*' && echo 'Found wildcard in Cluster Roles'"
        register: result413

      - debug:
          msg: "4.1.3 | FAILED | Minimize wildcard use in Roles and ClusterRoles (Manual).\n- {{ result413.stdout }}"
      - name: Get FAILED result
        set_fact:
          section4_tasks: '{{ section4_tasks | default([]) + [{ "task_number":"4.1.3","task_description":"Minimize wildcard use in Roles and ClusterRoles (Manual)","task_status":"FAILED","configuration":result413.stdout,"script":"" }] }}'

  delegate_to: 127.0.0.1
  become: false

- name: "4.1.4 | Minimize access to create pods (Manual)"
  block:
      - shell: "kubectl api-resources --sort-by name -o wide | grep -w Pod | cut -d'[' -f 2 | sed 's/.$//'"
        register: result414

      - debug:
          msg: "4.1.4 | FAILED | Minimize access to create pods (Manual).\n- Found: {{ result414.stdout | default(0) }}"

      - name: Get FAILED result
        set_fact:
          section4_tasks: '{{ section4_tasks | default([]) + [{ "task_number":"4.1.4","task_description":"Minimize access to create pods (Manual)","task_status":"FAILED","configuration":result414.stdout,"script":"" }] }}'

  delegate_to: 127.0.0.1
  become: false

- name: "4.1.5 | Ensure that default service accounts are not actively used.(Manual)"
  block:
      - shell: "kubectl api-resources --sort-by name -o wide | grep -w Pod | cut -d'[' -f 2 | sed 's/.$//'"
        register: result415

      - debug:
          msg: "4.1.5 | FAILED | Ensure that default service accounts are not actively used.(Manual).\n- Found: {{ result415.stdout | default(0) }}"
      - name: Get FAILED result
        set_fact:
          section4_tasks: '{{ section4_tasks | default([]) + [{ "task_number":"4.1.5","task_description":"Ensure that default service accounts are not actively used.(Manual)","task_status":"FAILED","configuration":result415.stdout,"script":"" }] }}'

  delegate_to: 127.0.0.1
  become: false

- name: "4.1.6 | Ensure that Service Account Tokens are only mounted where necessary (Manual)"
  block:
      - shell: "kubectl get rolebindings,clusterrolebindings --all-namespaces  -o custom-columns='KIND:kind,NAMESPACE:metadata.namespace,NAME:metadata.name,SERVICE_ACCOUNTS:subjects[?(@.kind==\"ServiceAccount\")].name' | grep -q default || echo 'Not found any binding'; kubectl get serviceaccount default -o yaml | grep 'automountServiceAccountToken: false' || echo 'Not found automountServiceAccountToken: false'"
        register: result416

      - debug:
          msg: "4.1.6 | FAILED | Ensure that Service Account Tokens are only mounted where necessary (Manual).\n- {{ result416.stdout }}"
      - name: Get FAILED result
        set_fact:
          section4_tasks: '{{ section4_tasks | default([]) + [{ "task_number":"4.1.6","task_description":"Ensure that Service Account Tokens are only mounted where necessary (Manual)","task_status":"FAILED","configuration":result416.stdout,"script":"" }] }}'

  delegate_to: 127.0.0.1
  become: false
