---
- name: "4.5.1 | Prefer using secrets as files over secrets as environment variables(Manual)"
  block:
      - shell: kubectl get all -o jsonpath='{range .items[?(@..secretKeyRef)]} {.kind} {.metadata.name} {"\n"}{end}' -A
        register: result451

      - debug:
          msg: "4.5.1 | NOT SCORED | Prefer using secrets as files over secrets as environment variables(Manual)."
      - name: Get NOT SCORED result
        set_fact:
          report_data: '{{ report_data | default([]) + [{ "task_number":"4.5.1","task_description":"Prefer using secrets as files over secrets as environment variables(Manual)","status":"NOT SCORED","configuration":"","remediation":"Script here" }] }}'

  delegate_to: 127.0.0.1

- name: "4.5.2 | Consider external secret storage (Manual)"
  block:
      - debug:
          msg: "4.5.2 | NOT SCORED | Consider external secret storage (Manual)."
      - name: Get NOT SCORED result
        set_fact:
          report_data: '{{ report_data | default([]) + [{ "task_number":"4.5.2","task_description":"Consider external secret storage (Manual)","status":"NOT SCORED","configuration":"","remediation":"Script here" }] }}'

  delegate_to: 127.0.0.1
