---
- name: "4.7.1 | Create administrative boundaries between resources using namespaces (Manual)"
  block:
      - shell: "kubectl get namespaces | awk 'BEGIN { ORS=\"; \" }; {if (NR!=1) print $1 }'"
        register: result471

      - debug:
          msg: "4.7.1 | FAILED | Create administrative boundaries between resources using namespaces (Manual)."
      - name: Get FAILED result
        set_fact:
          section4_tasks: '{{ section4_tasks | default([]) + [{ "task_number":"4.7.1","task_description":"Create administrative boundaries between resources using namespaces (Manual)","task_status":"FAILED","configuration":"","script":"" }] }}'

  delegate_to: 127.0.0.1
  become: false

- name: "4.7.2 | Apply Security Context to Your Pods and Containers (Manual)"
  block:
      - debug:
          msg: "4.7.2 | FAILED | Apply Security Context to Your Pods and Containers (Manual)."
      - name: Get FAILED result
        set_fact:
          section4_tasks: '{{ section4_tasks | default([]) + [{ "task_number":"4.7.2","task_description":"Apply Security Context to Your Pods and Containers (Manual)","task_status":"FAILED","configuration":"","script":"" }] }}'

  delegate_to: 127.0.0.1
  become: false

- name: "4.7.3 | The default namespace should not be used (Manual)"
  block:
      - shell: "kubectl get all -n default | awk 'BEGIN { ORS=\"; \" }; {if (NR!=1) print $1 }'"
        register: result471

      - debug:
          msg: "4.7.3 | FAILED | The default namespace should not be used (Manual)."
      - name: Get FAILED result
        set_fact:
          section4_tasks: '{{ section4_tasks | default([]) + [{ "task_number":"4.7.3","task_description":"The default namespace should not be used (Manual)","task_status":"FAILED","configuration":"","script":"" }] }}'

  delegate_to: 127.0.0.1
  become: false