---
- name: "4.3  | NOT SCORED | Azure Policy / OPA"
  block:
    - debug:
        msg: "4.3  | NOT SCORED | Azure Policy / OPA"
    - name: Get NOT SCORED result
      set_fact:
        report_data: '{{ report_data | default([]) + [{ "task_number":"4.3.0","task_description":"Azure Policy / OPA","status":"NOT SCORED","configuration":"","remediation":"Script here" }] }}'

  delegate_to: 127.0.0.1