---
- name: "4.3  | FAILED | Azure Policy / OPA"
  block:
    - debug:
        msg: "4.3  | FAILED | Azure Policy / OPA"
    - name: Get FAILED result
      set_fact:
        section4_tasks: '{{ section4_tasks | default([]) + [{ "task_number":"4.3.0","task_description":"Azure Policy / OPA","task_status":"FAILED","configuration":"","script":"" }] }}'

  delegate_to: 127.0.0.1
  become: false